@TodoApi_HostAddress = http://localhost:5067

POST {{TodoApi_HostAddress}}/api/todoitems
Content-Type: application/json

{
  "Name": "Walk Dog",
  "IsComplete": true
}

###

GET {{TodoApi_HostAddress}}/api/todoitems

### Get Request

@id=1
GET {{TodoApi_HostAddress}}/api/todoitems/{{id}}

###

@idToPut=3
PUT {{TodoApi_HostAddress}}/api/todoitems/{{idToPut}}
Content-Type: application/json

{
  "id": 3,
  "name": "feed fish",
  "isComplete": false
}

### Delete Request

@idToDelete=2
DELETE {{TodoApi_HostAddress}}/api/todoitems/{{id}}

###

PUT {{TodoApi_HostAddress}}/api/todoitems/{{id}}
Content-Type: application/json

{
  //TodoItem
}

###
